// *** WARNING: this file was generated by pulumi-gen-str. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Str
{
    public static class TrimPrefix
    {
        /// <summary>
        /// Trim a prefix from a string.
        /// </summary>
        public static Task<TrimPrefixResult> InvokeAsync(TrimPrefixArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<TrimPrefixResult>("str:index:trimPrefix", args ?? new TrimPrefixArgs(), options.WithDefaults());

        /// <summary>
        /// Trim a prefix from a string.
        /// </summary>
        public static Output<TrimPrefixResult> Invoke(TrimPrefixInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<TrimPrefixResult>("str:index:trimPrefix", args ?? new TrimPrefixInvokeArgs(), options.WithDefaults());
    }


    public sealed class TrimPrefixArgs : global::Pulumi.InvokeArgs
    {
        [Input("prefix", required: true)]
        public string Prefix { get; set; } = null!;

        [Input("string", required: true)]
        public string String { get; set; } = null!;

        public TrimPrefixArgs()
        {
        }
        public static new TrimPrefixArgs Empty => new TrimPrefixArgs();
    }

    public sealed class TrimPrefixInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("prefix", required: true)]
        public Input<string> Prefix { get; set; } = null!;

        [Input("string", required: true)]
        public Input<string> String { get; set; } = null!;

        public TrimPrefixInvokeArgs()
        {
        }
        public static new TrimPrefixInvokeArgs Empty => new TrimPrefixInvokeArgs();
    }


    [OutputType]
    public sealed class TrimPrefixResult
    {
        public readonly string Result;

        [OutputConstructor]
        private TrimPrefixResult(string result)
        {
            Result = result;
        }
    }
}
