# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .replace import *
from .trim_prefix import *
from .trim_suffix import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_str.regexp as __regexp
    regexp = __regexp
else:
    regexp = _utilities.lazy_import('pulumi_str.regexp')

_utilities.register(
    resource_modules="""
[]
""",
    resource_packages="""
[
 {
  "pkg": "str",
  "token": "pulumi:providers:str",
  "fqn": "pulumi_str",
  "class": "Provider"
 }
]
"""
)
