# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'TrimPrefixResult',
    'AwaitableTrimPrefixResult',
    'trim_prefix',
    'trim_prefix_output',
]

@pulumi.output_type
class TrimPrefixResult:
    def __init__(__self__, result=None):
        if result and not isinstance(result, str):
            raise TypeError("Expected argument 'result' to be a str")
        pulumi.set(__self__, "result", result)

    @property
    @pulumi.getter
    def result(self) -> str:
        return pulumi.get(self, "result")


class AwaitableTrimPrefixResult(TrimPrefixResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return TrimPrefixResult(
            result=self.result)


def trim_prefix(prefix: Optional[str] = None,
                string: Optional[str] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableTrimPrefixResult:
    """
    Trim a prefix from a string.
    """
    __args__ = dict()
    __args__['prefix'] = prefix
    __args__['string'] = string
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('str:index:trimPrefix', __args__, opts=opts, typ=TrimPrefixResult).value

    return AwaitableTrimPrefixResult(
        result=__ret__.result)


@_utilities.lift_output_func(trim_prefix)
def trim_prefix_output(prefix: Optional[pulumi.Input[str]] = None,
                       string: Optional[pulumi.Input[str]] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[TrimPrefixResult]:
    """
    Trim a prefix from a string.
    """
    ...
