// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../utilities";

// Export members:
export { MatchArgs, MatchResult, MatchOutputArgs } from "./match";
export const match: typeof import("./match").match = null as any;
export const matchOutput: typeof import("./match").matchOutput = null as any;
utilities.lazyLoad(exports, ["match","matchOutput"], () => require("./match"));

export { ReplaceArgs, ReplaceResult, ReplaceOutputArgs } from "./replace";
export const replace: typeof import("./replace").replace = null as any;
export const replaceOutput: typeof import("./replace").replaceOutput = null as any;
utilities.lazyLoad(exports, ["replace","replaceOutput"], () => require("./replace"));

export { SplitArgs, SplitResult, SplitOutputArgs } from "./split";
export const split: typeof import("./split").split = null as any;
export const splitOutput: typeof import("./split").splitOutput = null as any;
utilities.lazyLoad(exports, ["split","splitOutput"], () => require("./split"));

