// *** WARNING: this file was generated by pulumi-gen-str. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Match reports whether the string s contains any match of the regular expression pattern.
 */
export function match(args: MatchArgs, opts?: pulumi.InvokeOptions): Promise<MatchResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("str:regexp:match", {
        "pattern": args.pattern,
        "string": args.string,
    }, opts);
}

export interface MatchArgs {
    pattern: string;
    string: string;
}

export interface MatchResult {
    readonly matches: boolean;
}

export function matchOutput(args: MatchOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<MatchResult> {
    return pulumi.output(args).apply(a => match(a, opts))
}

export interface MatchOutputArgs {
    pattern: pulumi.Input<string>;
    string: pulumi.Input<string>;
}
