name: Publish

on:
  workflow_call:
    inputs:
      goreleaser-args:
        required: true
        type: string
      ref:
        required: true
        description: "GitHub ref to use"
        type: string
      use-pulumictl:
        type: boolean
        required: false
        default: true
        description: "Use pulumictl to derive a build tag"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags || true
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Install pulumictl
        if: ${{ inputs.use-pulumictl }}
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Set goreleaser Tag
        if: ${{ inputs.use-pulumictl }}
        run: |
          echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: ${{ inputs.goreleaser-args }}
          version: latest
